Repository GenericMappingTools/agu24workshop, pull requests merged in 2024-12, with the labels that each got.

#18 Tutorial 2: Fix typos
  README.md
  book/_toc.yml
  book/tut02_spe_pd_gpd.ipynb
  book/tut02_spec_pd_gpd.ipynb
Labels: enhancement, needs review

#15 Tutorial 3 - Add first draft of an xarray integration tutorial
  .gitignore
  .pre-commit-config.yaml
  book/_static/xarray.png
  book/_toc.yml
  book/tut03_spe_xarray.ipynb
  environment.yml
Labels: enhancement

#16 Tutorial 6. Animations
  book/_config.yml
  book/_toc.yml
  book/tut06_animation.rst
  book/tut06_animation_extended.rst
  environment.yml
Labels: enhancement, needs review

#21 Tutorial 1: fix figure display
  book/_static/tut01_colorbar_position.jpg
  book/_static/tut01_frame.jpg
  book/_static/tut01_projection.jpg
  book/_static/tut01_subplot.jpg
  book/tut01_firstfigure.ipynb
Labels: needs review

#12 Add getting started and installation instructions to the welcome page
  book/_toc.yml
  book/intro.md
Labels: documentation

#29 Standardize frontmatter across Tutorials
  book/intro.md
  book/tut01_firstfigure.ipynb
  book/tut02_spe_pd_gpd.ipynb
  book/tut03_spe_xarray.ipynb
  book/tut04_geophysics.ipynb
  book/tut05_topography.ipynb
  book/tut06_animation.rst
  book/tut06_animation_extended.rst
Labels: documentation, needs review, maintenance

#33 Overall fixes (typos, links, emojis, consistency, etc.)
  book/intro.md
  book/tut01_firstfigure.ipynb
  book/tut02_spe_pd_gpd.ipynb
  book/tut04_geophysics.ipynb
  book/tut05_topography.ipynb
  book/tut06_animation.rst
  book/tut06_animation_extended.rst
Labels: documentation, needs review

#34 Tutorial 01: Fix or update link to thumbnail image
  book/intro.md
Labels: maintenance

#35 Tutorial 02: Notes reading usage of own tabular data, dowload issue of river data
  book/tut02_spe_pd_gpd.ipynb
Labels: documentation, maintenance

#37 Tutorial 01: Mention "pygmt.Figure.savefig"
  book/tut01_firstfigure.ipynb
Labels: documentation, maintenance

#40 README: Add travel support for AGU24 by NSF grant EAR-1948602
  README.md
Labels: needs review, maintenance

#39 Tutorial 2: Change "gdf" to "gpd" in variable name | Show output of ".head()" and ".crs" explicitly
  book/tut01_firstfigure.ipynb
  book/tut02_spe_pd_gpd.ipynb
Labels: needs review, maintenance
